### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.transforms'

### ISSUE THREAD

**Issue by soltkreig** [TaatiTeam/MotionAGFormer#48]
Hi! I'm trying to run vis.py, but get the error:
Traceback (most recent call last):
  File "demo/vis.py", line 5, in <module>
    from lib.hrnet.gen_kpts import gen_video_kpts as hrnet_pose
  File "/home/jovyan/people/murtazin/MotionAGFormer/demo/lib/hrnet/gen_kpts.py", line 21, in <module>
    from lib.hrnet.lib.utils.inference import get_final_preds
  File "/home/jovyan/people/murtazin/MotionAGFormer/demo/lib/hrnet/lib/utils/inference.py", line 19, in <module>
    from utils.transforms import transform_preds
ModuleNotFoundError: No module named 'utils.transforms'
![image](https://github.com/user-attachments/assets/ee4bed37-3ec3-4f30-a28d-3437f15521ed)

**Comment by soltkreig** [comment]
Fix with adding `__init__.py` to folder

**Comment by l2day** [comment]
> 修复添加`__init__.py`到文件夹的问题

Hello, may I ask how you specifically modified it? Thank you for your reply.
